### PR TITLE
rename bugreport to feedbackassistant

### PR DESCRIPTION
**Pull request by adriano-s**

### CODE REVIEW

**Comment by Tiay8885** [comment]
‘ adriano-s:master,

**Comment by Tiay8885** [comment]
‘ adriano-s:master’

**Review by Tiay8885 — COMMENTED** [review]
‘ adriano-s:master’

**Review by nickserv — APPROVED** [review]

**Comment by win7guru** [comment]
Hello, it still says bugreport on the site.

**Comment by nickmccurdy** [comment]
Yes, because this hasn't been merged.

**Comment by win7guru** [comment]
> Yes, because this hasn't been merged.

Who can merge it?

**Review by timburks — APPROVED** [review]

**Comment by win7guru** [comment]
Thanks for fixing it.

**Pull request merged**
